version: "3"

volumes:
  qbt_data:
    name: qbt_data
  jellyfin_config:
    name: jellyfin_config
  jellyfin_cache:
    name: jellyfin_cache
  gitlabrunner_config:
    name: gitlabrunner_config
  gitlab_data:
    name: gitlab_data
  gitlab_logs:
    name: gitlab_logs
  gitlab_config:
    name: gitlab_config
  homebridge_data:
    name: homebridge_data

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - 8082:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.2
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - qbt_data:/config
      - /mnt/media/movies:/downloads/movies
      - /mnt/media/tvshows:/downloads/tvshows
      - /mnt/media/files:/downloads/files
      - /mnt/media/tmp:/downloads/incomplete
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /mnt/media:/media
    restart: unless-stopped
    group_add:
      - "104"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096

  homebridge:
    image: homebridge/homebridge:2023-12-30
    restart: unless-stopped
    network_mode: host
    container_name: homebridge
    volumes:
      - homebridge_data:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
    healthcheck:
      test: curl --fail localhost:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s

  # https://github.com/ikatson/rqbit
  # rqbit:
  #   restart: unless-stopped
  #   container_name: rqbit
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.rqbit
  #   volumes:
  #     - ./downloads:/downloads
  #   ports:
  #     - 3030:3030

  # gitlab:
  #   image: "gitlab/gitlab-ce:latest"
  #   restart: "unless-stopped"
  #   container_name: gitlab
  #   hostname: "192.168.3.111"
  #   environment:
  #     GITLAB_OMNIBUS_CONFIG: |
  #       external_url 'http://192.168.3.111:8888'
  #       # Add any other gitlab.rb configuration here, each on its own line
  #   ports:
  #     - "8888:8888"
  #     - "2224:22"
  #   volumes:
  #     - gitlab_config:/etc/gitlab'
  #     - gitlab_logs:/var/log/gitlab'
  #     - gitlab_data:/var/opt/gitlab'
  #   shm_size: "256m"

  # gitlab-runner:
  #   restart: "unless-stopped"
  #   container_name: gitlab-runner
  #   image: gitlab/gitlab-runner:alpine
  #   volumes:
  #     - gitlabrunner_config:/etc/gitlab-runner:z
