version: "3"

volumes:
  qbt_data:
    name: qbt_data
  jellyfin_config:
    name: jellyfin_config
  jellyfin_cache:
    name: jellyfin_cache
  gitlabrunner_config:
    name: gitlabrunner_config
  gitlab_data:
    name: gitlab_data
  gitlab_logs:
    name: gitlab_logs
  gitlab_config:
    name: gitlab_config
  homebridge_data:
    name: homebridge_data

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - 8082:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.2
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - qbt_data:/config
      - /mnt/media/movies:/downloads/movies
      - /mnt/media/tvshows:/downloads/tvshows
      - /mnt/media/files:/downloads/files
      - /mnt/media/tmp:/downloads/incomplete
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /mnt/media:/media
    restart: unless-stopped
    group_add:
      - "104"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096

  homebridge:
    image: homebridge/homebridge:latest
    restart: unless-stopped
    network_mode: host
    container_name: homebridge
    volumes:
      - homebridge_data:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
    healthcheck:
      test: curl --fail localhost:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s

  gitlab:
    image: "gitlab/gitlab-ce:16.1.1"
    restart: "unless-stopped"
    container_name: gitlab
    hostname: "192.168.3.111"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.3.111:8888'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "8888:8888"
      # - "443:443"
      - "2224:2224"
    volumes:
      - gitlab_config:/etc/gitlab'
      - gitlab_logs:/var/log/gitlab'
      - gitlab_data:/var/opt/gitlab'
    shm_size: "256m"

  gitlab-runner:
    restart: "unless-stopped"
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:alpine
    volumes:
      - gitlabrunner_config:/etc/gitlab-runner:z

  # filebrowser:
  #   container_name: filebrowser
  #   image: hurlenko/filebrowser:latest
  #   ports:
  #     - 8088:8080
  #   volumes:
  #     - /:/data
  #     - filebrowser_data:/config
  #     - qbt_data:/data/qbt_data
  #   environment:
  #     - FB_BASEURL=/
  #     - FB_NOAUTH
  #   restart: unless-stopped

  # homeassistant:
  #   container_name: homeassistant
  #   image: ghcr.io/home-assistant/home-assistant:stable
  #   volumes:
  #     - homeassistant_data:/config
  #     - /etc/localtime:/etc/localtime:ro
  #   restart: unless-stopped
  #   privileged: true
  #   network_mode: host
  #   environment:
  #     - TZ=Europe/Kyiv

  # matter-server:
  #   image: ghcr.io/home-assistant-libs/python-matter-server:stable
  #   container_name: matter-server
  #   restart: unless-stopped
  #   # Required for mDNS to work correctly
  #   network_mode: host
  #   security_opt:
  #     # Needed for Bluetooth via dbus
  #     - apparmor:unconfined
  #   volumes:
  #     # Create an .env file that sets the USERDIR environment variable.
  #     - ${USERDIR:-$HOME}/docker/matter-server/data:/data/
  #     - /run/dbus:/run/dbus:ro
