version: "3"

volumes:
  qbt_data:
    name: qbt_data
  filebrowser_data:
    name: filebrowser_data
  homeassistant_data:
    name: homeassistant_data
  switchbotmqtt_data:
    name: switchbotmqtt_data

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - 8082:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - qbt_data:/config
      - /mnt/usb1:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  filebrowser:
    container_name: filebrowser
    image: hurlenko/filebrowser:latest
    ports:
      - 8088:8080
    volumes:
      - /:/data
      - filebrowser_data:/config
      - qbt_data:/data/qbt_data
    environment:
      - FB_BASEURL=/
      - FB_NOAUTH
    restart: unless-stopped

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - homeassistant_data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Kyiv

  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    # Required for mDNS to work correctly
    network_mode: host
    security_opt:
      # Needed for Bluetooth via dbus
      - apparmor:unconfined
    volumes:
      # Create an .env file that sets the USERDIR environment variable.
      - ${USERDIR:-$HOME}/docker/matter-server/data:/data/
      - /run/dbus:/run/dbus:ro
